import Head from 'next/head';
import Link from 'next/link';
import { motion, AnimatePresence } from 'framer-motion';
import { useContext } from 'react';
import styled, { ThemeContext } from 'styled-components';
import Toggle from '../components/Toggle';

const Container = styled.div`
  position: fixed;
  padding: 0;
  margin: 0;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  display: grid;
  grid-template-areas:
    'edu edu proj'
    'about main proj'
    'about con con';
`;

const MainStyled = styled(motion.div)`
  display: grid;
  border: 1.5em solid ${({ theme }) => theme.secondaryColor};
  font-weight: bold;
  grid-area: main;
  font-family: ExtraBold 800 Italic;
  justify-content: center;
  align-content: center;
  font-size: 3em;
  > a {
    color: ${({ theme }) => theme.textTwo};
  }
`;

const Edu = styled(motion.div)`
  display: grid;
  border: 1.5em solid ${({ theme }) => theme.primaryColor};
  color: ${({ theme }) => theme.textThree};
  grid-area: edu;
  justify-content: center;
  align-content: center;
  font-family: 'Merriweather', serif;
  font-size: 3em;
  background-color: ${({ theme }) => theme.secondaryColor};
  > a {
    color: ${({ theme }) => theme.textThree};
  }
`;

const Proj = styled(motion.div)`
  display: grid;
  border: 1.5em solid ${({ theme }) => theme.thirdColor};
  color: ${({ theme }) => theme.textThree};
  grid-area: proj;
  justify-content: center;
  align-content: center;
  font-family: 'Merriweather', serif;
  font-size: 3em;
  background-color: ${({ theme }) => theme.secondaryColor};
  > a {
    color: ${({ theme }) => theme.textThree};
  }
`;

const About = styled(motion.div)`
  display: grid;
  border: 1.5em solid ${({ theme }) => theme.thirdColor};
  color: ${({ theme }) => theme.textThree};
  grid-area: about;
  justify-content: center;
  align-content: center;
  font-family: 'Merriweather', serif;
  font-size: 3em;
  background-color: ${({ theme }) => theme.secondaryColor};
  > a {
    color: ${({ theme }) => theme.textThree};
  }
`;

const Con = styled(motion.div)`
  display: grid;
  border: 1.5em solid ${({ theme }) => theme.primaryColor};
  font-size: 3em;
  grid-area: con;
  justify-content: center;
  align-content: center;
  font-family: 'Merriweather', serif;
  background-color: ${({ theme }) => theme.secondaryColor};
  > a {
    color: ${({ theme }) => theme.textThree};
  }
`;

const styledA = styled(motion.a)``;

export default function Home() {
  const { id, setTheme } = useContext(ThemeContext);

  const mainVar = {
    start: {
      opacity: 0,
    },
    show: {
      opacity: 1,
      transition: {
        duration: 1.6,
        delay: 4,
        delayChildren: 4,
      },
    },
  };
  const mainWordsVar = {
    start: {
      scale: 1,
    },
    show: {
      scale: [1, 2, 1],
      transition: {
        duration: 2,
      },
    },
  };
  const eduVar = {
    hidden: {
      x: -2000,
    },
    show: {
      x: 0,
      transition: {
        duration: 2,
        delay: 0.5,
      },
    },
    hover: {
      scale: 1.3,
    },
  };
  const aboutVar = {
    hidden: {
      y: -2000,
    },
    show: {
      y: 0,
      transition: {
        duration: 2,
        delay: 1,
      },
    },
    hover: {
      scale: 1.3,
    },
  };
  const projVar = {
    hidden: {
      x: -2000,
    },
    show: {
      x: 0,
      transition: {
        duration: 2,
        delay: 1.5,
      },
    },
    hover: {
      scale: 1.3,
    },
  };
  const conVar = {
    hidden: {
      x: -2000,
    },
    show: {
      x: 0,
      transition: {
        duration: 2,
        delay: 2,
      },
    },
    hover: {
      scale: 1.3,
    },
  };
  const toggleVar = {
    hidden: {
      x: 2000,
    },
    show: {
      x: 0,
    },
    transition: {
      duration: 2,
      delay: 6,
    },
  };
  return (
    <>
      <Container>
        <Head>
          <title>{`Ed's Portfolio`}</title>
          <meta name='description' content='Generated by create next app' />
        </Head>
        <MainStyled
          key='main'
          variants={mainVar}
          initial='start'
          animate='show'
        >
          <motion.h1
            key='mainWords'
            variants={mainWordsVar}
            initial='start'
            animate='show'
          >{`Ed O'Connor`}</motion.h1>

          <motion.div
            key='toggle'
            variants={toggleVar}
            initial='hidden'
            animate='show'
          >
            <Toggle isActive={id === 'fun'} onToggle={setTheme} />
          </motion.div>
        </MainStyled>

        <Edu
          key='edu'
          variants={eduVar}
          whileHover='hover'
          initial='hidden'
          animate='show'
        >
          <a>
            <Link href='/education' passHref>
              <h2>{`Education`}</h2>
            </Link>
          </a>
        </Edu>
        <Proj key='projDiv' variants={projVar} whileHover='hover'>
          <a>
            <Link href='/projects' passHref>
              <motion.h2
                key='proj'
                variants={projVar}
                initial='hidden'
                animate='show'
              >{`Projects`}</motion.h2>
            </Link>
          </a>
        </Proj>
        <About key='aboutDiv' variants={aboutVar} whileHover='hover'>
          <a>
            <Link href='/about' passHref>
              <motion.h2
                key='about'
                variants={aboutVar}
                initial='hidden'
                animate='show'
              >{`About`}</motion.h2>
            </Link>
          </a>
        </About>
        <Con
          key='con'
          variants={conVar}
          whileHover='hover'
          initial='hidden'
          animate='show'
        >
          <a>
            <Link href='/contact' passHref>
              <h2>{`Contact`}</h2>
            </Link>
          </a>
        </Con>
      </Container>
    </>
  );
}
