import Head from 'next/head';
import Link from 'next/link';
import { useContext } from 'react';
import styled, { ThemeContext } from 'styled-components';

import Toggle from '../components/Toggle';

const Container = styled.div`
  position: fixed;
  padding: 0;
  margin: 0;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  display: grid;
  grid-template-areas:
    'edu edu proj'
    'about main proj'
    'about con con';
`;

const MainStyled = styled.div`
  display: grid;
  border: 1.5em solid ${({ theme }) => theme.secondaryColor};
  font-weight: bold;
  grid-area: main;
  font-family: ExtraBold 800 Italic;
  justify-content: center;
  align-content: center;
  font-size: 3em;
  > a {
    color: ${({ theme }) => theme.textTwo};
  }
`;

const Edu = styled.div`
  display: grid;
  border: 1.5em solid ${({ theme }) => theme.primaryColor};
  color: ${({ theme }) => theme.textThree};
  grid-area: edu;
  justify-content: center;
  align-content: center;
  font-family: 'Merriweather', serif;
  font-size: 3em;
  > a {
    color: ${({ theme }) => theme.textThree};
  }
`;

const Proj = styled.div`
  display: grid;
  border: 1.5em solid ${({ theme }) => theme.thirdColor};
  color: ${({ theme }) => theme.textThree};
  grid-area: proj;
  justify-content: center;
  align-content: center;
  font-family: 'Merriweather', serif;
  font-size: 3em;
  > a {
    color: ${({ theme }) => theme.textThree};
  }
`;

const About = styled.div`
  display: grid;
  border: 1.5em solid ${({ theme }) => theme.thirdColor};
  color: ${({ theme }) => theme.textThree};
  grid-area: about;
  justify-content: center;
  align-content: center;
  font-family: 'Merriweather', serif;
  font-size: 3em;
  > a {
    color: ${({ theme }) => theme.textThree};
  }
`;

const Con = styled.div`
  display: grid;
  border: 1.5em solid ${({ theme }) => theme.primaryColor};

  font-size: 3em;
  grid-area: con;
  justify-content: center;
  align-content: center;
  font-family: 'Merriweather', serif;
  > a {
    color: ${({ theme }) => theme.textThree};
  }
`;

export default function Home() {
  const { id, setTheme } = useContext(ThemeContext);

  return (
    <>
      <Container>
        <Head>
          <title>{`Ed's Portfolio`}</title>
          <meta name='description' content='Generated by create next app' />
        </Head>

        <MainStyled>
          <Link href='/'>
            <a>{`Ed O'Connor`}</a>
          </Link>
          <Toggle isActive={id === 'fun'} onToggle={setTheme} />
        </MainStyled>
        <Edu>
          <Link href='/education'>
            <a>{`Education`}</a>
          </Link>
        </Edu>
        <Proj>
          <Link href='/projects'>
            <a>{`Projects`}</a>
          </Link>
        </Proj>
        <About>
          <Link href='/about'>
            <a>{`About`}</a>
          </Link>
        </About>
        <Con>
          <Link href='/contact'>
            <a>{`Contact`}</a>
          </Link>
        </Con>
      </Container>
    </>
  );
}
