import Head from 'next/head';
import Link from 'next/link';
import { useContext } from 'react';
import styled, { ThemeContext } from 'styled-components';

import Toggle from '../components/Toggle';

const Container = styled.div`
  position: fixed;
  padding: 0;
  margin: 0;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  display: grid;
  grid-template-areas:
    'edu edu proj'
    'about main proj'
    'about con con';
`;

const MainStyled = styled.div`
  display: grid;
  border: 1.5em solid ${({ theme }) => theme.secondaryColor};
  color: ${({ theme }) => theme.primaryColor};
  font-weight: bold;
  grid-area: main;
  font-family: ExtraBold 800 Italic;
  justify-content: center;
  align-content: center;
  font-size: 3em;
`;

const Edu = styled.div`
  display: grid;
  border: 1.5em solid ${({ theme }) => theme.primaryColor};
  color: ${({ theme }) => theme.textOne};
  grid-area: edu;
  justify-content: center;
  align-content: center;
  font-family: 'Merriweather', serif;
  font-size: 3em;
`;

const Proj = styled.div`
  display: grid;
  border: 1.5em solid ${({ theme }) => theme.thirdColor};
  color: ${({ theme }) => theme.textOne};
  grid-area: proj;
  justify-content: center;
  align-content: center;
  font-family: 'Merriweather', serif;
  font-size: 3em;
`;

const About = styled.div`
  display: grid;
  border: 1.5em solid ${({ theme }) => theme.thirdColor};
  color: ${({ theme }) => theme.textOne};
  grid-area: about;
  justify-content: center;
  align-content: center;
  font-family: 'Merriweather', serif;
  font-size: 3em;
`;

const Con = styled.div`
  display: grid;
  border: 1.5em solid ${({ theme }) => theme.primaryColor};
  color: #035397;
  font-size: 3em;
  grid-area: con;
  justify-content: center;
  align-content: center;
  font-family: 'Merriweather', serif;
`;

export default function Home() {
  const { id, setTheme } = useContext(ThemeContext);
  console.log(process.env.NEXT_PUBLIC_YOUR_SERVICE_ID);
  console.log(process.env.NEXT_PUBLIC_YOUR_PUBLIC_KEY);
  console.log(process.env.NEXT_PUBLIC_YOUR_TEMPLATE_ID);

  return (
    <>
      <Container>
        <Head>
          <title>{`Ed's Portfolio`}</title>
          <meta name='description' content='Generated by create next app' />
        </Head>

        <MainStyled>
          <Link href='/'>{`Ed O'Connor`}</Link>
          <Toggle isActive={id === 'fun'} onToggle={setTheme} />
        </MainStyled>
        <Edu>
          <Link href='/education'>{`Education`}</Link>
        </Edu>
        <Proj>
          <Link href='/projects'>{`Projects`}</Link>
        </Proj>
        <About>
          <Link href='/about'>{`About`}</Link>
        </About>
        <Con>
          <Link href='/contact'>{`Contact`}</Link>
        </Con>
      </Container>
    </>
  );
}
